name: CD

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:      
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies using pipenv
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --dev
    
    - name: Serverless install python-requirements plugin
      uses: serverless/github-action@master
      with:
        args: plugin install --name serverless-python-requirements    
  
    - name: Deploy to AWS using Serverless
      uses: serverless/github-action@master
      with:
        args: deploy    
      
